// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Common;
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Answers : BaseEntity
{
    public int Question { get; set; }

    public int User { get; set; }

    public int AnswerValue { get; set; }

    public bool Correct { get; set; }

    public bool Bonus { get; set; }

    public virtual Questions QuestionNavigation { get; set; }

    public virtual Users UserNavigation { get; set; }
}