// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Common;
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Questions : BaseEntity
{
    public int Owner { get; set; }

    public string Question { get; set; }

    public string FirstOption { get; set; }

    public string SecondOption { get; set; }

    public string ThirdOption { get; set; }

    public string FourthOption { get; set; }

    public string FifthOption { get; set; }

    public int CorrectAnswer { get; set; }

    public int? SecretNumber { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    public virtual Users OwnerNavigation { get; set; }
}