// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Common;
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Users : BaseEntity
{
    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Name { get; set; }

    public bool Admin { get; set; }

    public int Score { get; set; }

    public bool Ativated { get; set; }

    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();
}